webtalk_init -webtalk_dir C:/Users/levim/Desktop/pmodDA3/dds/dds.sim/sim_1/behav/xsim/xsim.dir/tb_dds_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 21 14:56:14 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2288692" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9f86bfdbdfc45c8cb62219a4ee1b87fd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "15a81b72c7884bf58a34066a4b0e89c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "20" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9364_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3896363789 -regid "" -xml C:/Users/levim/Desktop/pmodDA3/dds/dds.sim/sim_1/behav/xsim/xsim.dir/tb_dds_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/levim/Desktop/pmodDA3/dds/dds.sim/sim_1/behav/xsim/xsim.dir/tb_dds_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/levim/Desktop/pmodDA3/dds/dds.sim/sim_1/behav/xsim/xsim.dir/tb_dds_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
